# Generated by Django 4.0.4 on 2022-05-28 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(default='static/blog/assests/index.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 14, 4, 13, 103926, tzinfo=utc)),
        ),
    ]
